const camelToKebab = (str) =>
	str
		// Look for any lowercase letter followed by an uppercase letter
		.replaceAll("_", "-")
		.replace(/([a-z0-9])([A-Z])/g, "$1-$2")
		// Convert the entire string to lowercase
		.toLowerCase();

const times = (n, f) => {
	const r = new Array(n);
	for (let i = 0; i < n; i++) {
		r[i] = f(i);
	}
	return r;
};

function* properties(value, k) {
	if (Object.getPrototypeOf(value) === Object.prototype) {
		for (const kk in value) {
			for (const v of properties(
				value[kk],
				k ? `${camelToKebab(k)}-${camelToKebab(kk)}` : camelToKebab(kk)
			)) {
				yield v;
			}
		}
	} else {
		yield k ? [k, value] : [null, value];
	}
}

class Rule {
	constructor(selectors, properties) {
		this.selectors = selectors;
		this.properties = properties;
	}
	*lines() {
		yield `${this.selectors ? this.selectors.join(", ") : "*"} {`;
		for (const k in this.properties) {
			yield `\t${k}: ${this.properties[k]};`;
		}
		yield "}";
	}
}
const rule = (selector, ...body) => {
	// TODO: We could do basic selector parsing to extract classnames, tagnames
	// and ids.
	const sel = selector instanceof Array ? selector : [selector];
	const props = {};
	for (const b of body) {
		if (typeof b === "string") {
			for (let line of b.split("\n")) {
				line = line.trim("");
				if (line.endsWith(";")) {
					line = line.substring(0, line.length - 1);
				}
				const i = line.indexOf(":");
				if (!line.startsWith("//") && i >= 0) {
					props[line.substring(0, i).trim()] = line
						.substring(i + 1)
						.trim();
				}
			}
		} else {
			for (const [k, v] of properties(b)) {
				props[k] = v;
			}
		}
		return new Rule(sel, props);
	}
};

// --
// Scope defines variables, and allows to keep track of them.
class Scope {
	// NOTE: It is a bit awkward
	static get(target, property) {
		return typeof property === "string" &&
			property !== "_name" &&
			property != "walk"
			? (target[property] = target[property] ?? scope(property, target))
			: target[property];
	}
	static set(target, property, value) {
		// TODO: We should have the vars in a map instead
		target[property] = value;
	}
	constructor(name, parent) {
		this._name = parent?._name ? `${parent._name}-${name}` : name;
	}
	*walk() {
		for (const k in this) {
			if (typeof k === "string" && k !== "_name") {
				if (this[k] instanceof Scope) {
					for (const _ of this[k].walk()) {
						yield _;
					}
				} else {
					yield this._name;
				}
			}
		}
	}
	toString() {
		return `var(--${this._name})`;
	}
}
const scope = (name, parent) =>
	new Proxy(name instanceof Scope ? name : new Scope(name, parent), Scope);
const Vars = new Scope();
const vars = scope(Vars);

// --
// Pseudo-selectors support
const pseudo = (type, ...selectors) => {
	let res = [];
	for (const s of selectors) {
		if (s instanceof Array) {
			res = res.concat(pseudo(type, ...s));
		} else {
			res.push(`${s}:${type}`);
		}
	}
	return res;
};
const on = new Proxy(
	{},
	{
		get: (target, property) =>
			typeof property === "string"
				? (target[property] =
						target[property] ??
						((...sel) => pseudo(property, ...sel)))
				: target[property],
	}
);

class Group {
	constructor(contents, name = undefined) {
		this.contents = contents;
		this.name = name;
	}
	*rules() {
		for (const r of this.contents) {
			if (r instanceof Meta) {
				// pass
			} else if (r instanceof Group) {
				for (const _ of r.rules()) {
					yield _;
				}
			} else {
				yield r;
			}
		}
	}

	*lines() {
		if (this.name) {
			yield `/* @${this.constructor.name.toLowerCase()} ${this.name} */`;
		}
		for (const r of this.contents) {
			for (const _ of r.lines()) {
				yield _;
			}
		}
		if (this.name) {
			yield `/* @end ${this.name} */`;
		}
	}
}
const group = (...rules) => new Group(rules);
class Layer extends Group {}
const layer = (...rules) => new Layer(rules);

class Meta {
	constructor(value) {
		this.value = value;
	}
}
class Documentation extends Meta {}
const doc = (value) => new Documentation(value);

const named = (mapping) => {
	const items = [];
	for (const k in mapping) {
		const v = mapping[k];
		if (v instanceof Group) {
			v.name = k;
			items.push(v);
		} else {
			items.push(new Group(v instanceof Array ? v : v ? [v] : [], k));
		}
	}
	return new Group(items);
};

function* css(...values) {
	yield `/* Generated by LittleCSS */`;
	for (const v of values) {
		for (const l of v.lines()) {
			yield l;
		}
	}
	yield "/* EOF */";
}

export { Vars, on, vars, rule, times, layer, group, css, named, doc };
export default css;
// EOF
